---
- segment: kafkaconsumer
  config:
    server: kafka01.bwnf.belwue.de:9093
    topic: flow-messages-enriched
    group: naegele-flowpipeline-consumer
    user: naegele
    pass: $KAFKA_SASL_PASS
- segment: kafkaproducer
  config:
    server: localhost:9092
    topic: flows
    group: test
    notls: 1
    noauth: 1
